# To execute this docker-compose yml file use 'docker-compose -f <file_name> up'
# Add the '-d' flag at the end for detached execution
#docker run -d -p 4444:4444 --name <container-name> <image-name> 
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: chrome
    depends_on:
      - selenium-hub
      
    environment:
      - HUB_HOST=selenium-hub
  firefox:
    image: selenium/node-firefox:3.141.59
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
